### PR TITLE
Basic Javascript updates 7

### PR DESCRIPTION
**Pull request by abhisekp**
Updates since https://gitter.im/abhisekp/FreeCodeCamp/CurriculumDevelopment?at=567f9c9c66a282570f90433f

closes FreeCodeCamp/FreeCodeCamp#5495
closes FreeCodeCamp/FreeCodeCamp#5494
closes FreeCodeCamp/FreeCodeCamp#5493
closes FreeCodeCamp/FreeCodeCamp#5492
closes FreeCodeCamp/FreeCodeCamp#5491
closes FreeCodeCamp/FreeCodeCamp#5490
closes FreeCodeCamp/FreeCodeCamp#5488
closes FreeCodeCamp/FreeCodeCamp#5486
closes FreeCodeCamp/FreeCodeCamp#5487
closes FreeCodeCamp/FreeCodeCamp#5483
closes FreeCodeCamp/FreeCodeCamp#5482

### CODE REVIEW

**Comment by abhisekp** [comment]
closes FreeCodeCamp/FreeCodeCamp#5495

**Comment by abhisekp** [comment]
closes FreeCodeCamp/FreeCodeCamp#5494

**Comment by abhisekp** [comment]
closes FreeCodeCamp/FreeCodeCamp#5493

**Comment by abhisekp** [comment]
closes FreeCodeCamp/FreeCodeCamp#5492

**Comment by abhisekp** [comment]
Closes FreeCodeCamp/FreeCodeCamp#5491

**Comment by abhisekp** [comment]
Closes FreeCodeCamp/FreeCodeCamp#5491

**Comment by abhisekp** [comment]
Closes FreeCodeCamp/FreeCodeCamp#5490

**Comment by abhisekp** [comment]
Closes FreeCodeCamp/FreeCodeCamp#5488

**Comment by abhisekp** [comment]
Closes FreeCodeCamp/FreeCodeCamp#5486

**Comment by SaintPeter** [comment]
All of the "Closes" messages need to be in the main commit to take effect.

**Comment by abhisekp** [comment]
@SaintPeter Good to Go :+1:

**Comment by abhisekp** [comment]
@SaintPeter Good to Go :+1:

**Pull request merged**
